from page_objects.Login.login import Login
from page_objects.TaskList.TaskList import TaskList
import time


# import pyautogui


class TestTaskList:
    baseURL = "https://uat.worklenz.com"
    email = "foveya5340@akoption.com"
    password = "ceyDigital#000"
    TaskName = "Task 01"
    searchMember = "k"
    labelName = "Automation Testing"
    subTaskName = "Sub task"
    NewTaskName = " Task 02"
    ParentTaskName = "Task 01"
    NewCategoryName = "Have to do"
    anotherTask = "Task 03"
    tempName = "Temp Task"

    def test_task_list(self, setup):
        self.browser = setup
        self.browser.get(self.baseURL)
        self.lg = Login(self.browser)
        self.lg.clickLogin()
        time.sleep(3)
        self.lg.setEmail(self.email)
        self.lg.setpassword(self.password)
        time.sleep(3)
        self.lg.submit()
        time.sleep(10)
        self.ti = TaskList(self.browser)
        time.sleep(3)
        self.ti.clickProjectTab()
        time.sleep(3)
        self.ti.selectProject()
        time.sleep(3)
        self.ti.clickToDo()
        time.sleep(3)
        self.ti.clickAddTask()
        time.sleep(3)
        self.ti.enterTask(self.TaskName)
        time.sleep(3)
        self.ti.clickMemberAssign()
        time.sleep(3)
        self.ti.searchMember(self.searchMember)
        time.sleep(3)
        self.ti.selectMember()
        time.sleep(3)
        self.ti.clickOkButton()
        time.sleep(3)
        self.ti.clickLabel()
        time.sleep(3)
        self.ti.createLabel(self.labelName)
        time.sleep(3)
        self.ti.selectLabel()
        time.sleep(3)
        self.ti.clickStatus()
        time.sleep(3)
        self.ti.status_doing()
        time.sleep(3)
        self.ti.clickPriority()
        time.sleep(3)
        self.ti.priorityHigh()
        time.sleep(5)
        self.ti.scroll_right()
        time.sleep(5)
        self.ti.timeLogStart()
        time.sleep(3)
        self.ti.timeLogPause()
        time.sleep(3)
        self.ti.timeLogDetails()
        time.sleep(3)
        self.ti.dueDate()
        time.sleep(3)
        self.ti.selectDueDate()
        time.sleep(3)
        self.ti.scroll_left()
        time.sleep(5)
        self.ti.subTask()
        time.sleep(3)
        self.ti.subTaskOpen()
        time.sleep(3)
        self.ti.subTaskEnter(self.subTaskName)
        time.sleep(3)
        self.ti.subTaskClose()
        time.sleep(3)
        self.ti.taskRightClick1()
        time.sleep(3)
        self.ti.assignToMe()
        time.sleep(3)
        self.ti.taskRightClick1()
        time.sleep(3)
        self.ti.moveTo()
        time.sleep(3)
        self.ti.moveToDone()
        time.sleep(3)
        self.ti.scrollDown()
        time.sleep(3)
        self.ti.taskRightClick2()
        time.sleep(3)
        self.ti.archiveSelect()
        time.sleep(3)
        self.ti.viewArchives()
        time.sleep(5)
        self.ti.taskRightClick3()
        time.sleep(3)
        self.ti.unArchived()
        time.sleep(3)
        self.ti.showArchived()
        time.sleep(3)
        self.ti.addTaskNew()
        time.sleep(3)
        self.ti.typeTask(self.NewTaskName)
        time.sleep(3)
        self.ti.taskRightClick4()
        time.sleep(3)
        self.ti.convertToSubTask()
        time.sleep(3)
        self.ti.searchParentTask(self.ParentTaskName)
        time.sleep(3)
        self.ti.selectParentTask()
        time.sleep(3)
        self.ti.openParentTask()
        time.sleep(3)
        self.ti.taskRightClick5()
        time.sleep(3)
        self.ti.deleteTask()
        time.sleep(3)
        self.ti.categoryDont()
        time.sleep(3)
        self.ti.renameCategory()
        time.sleep(3)
        self.ti.renameType(self.NewCategoryName)
        time.sleep(3)
        # self.ti.categoryDont()
        # time.sleep(3)
        # self.ti.categoryChange()
        # time.sleep(3)
        # self.ti.categoryChangeTodo()
        # time.sleep(3)
        # self.ti.openHaveToDOCategory()
        # time.sleep(3)
        self.ti.addTask()
        time.sleep(3)
        self.ti.typeTaskN(self.anotherTask)
        time.sleep(3)
        self.ti.taskRightClick6()
        time.sleep(3)
        self.ti.bottomActionStatus()
        time.sleep(3)
        self.ti.status_doing()
        time.sleep(3)
        self.ti.taskRightClick7()
        time.sleep(3)
        self.ti.changeLabel()
        time.sleep(3)
        self.ti.selectLabelN()
        time.sleep(3)
        self.ti.apply()
        time.sleep(3)
        self.ti.taskRightClick8()
        time.sleep(3)
        self.ti.assignToMeN()
        time.sleep(3)
        self.ti.taskRightClick9()
        time.sleep(3)
        self.ti.archive()
        time.sleep(3)
        self.ti.showArchive()
        time.sleep(3)
        self.ti.taskRightClick2()
        time.sleep(3)
        self.ti.unArchived()
        time.sleep(3)
        self.ti.showUnArchived()
        time.sleep(3)
        self.ti.taskRightClick11()
        time.sleep(3)
        self.ti.moreOption()
        time.sleep(3)
        self.ti.createTemp()
        time.sleep(3)
        self.ti.tempName(self.tempName)
        time.sleep(3)
        self.ti.saveBtn()
        time.sleep(3)
        self.ti.taskRightClick12()
        time.sleep(3)
        self.ti.deleteTaskN()
        time.sleep(3)








