from page_objects.Login.login import Login
from page_objects.Roadmap.Roadmap import Roadmap
import time
from utilities.readProperties import ReadConfig
from self import self
from test_data.test_data import ProjectRoadmapData


class TestRoadmap:
    baseURL = ReadConfig.get_application_url(self)
    email = ReadConfig.get_email()
    password = ReadConfig.get_password()

    def test_roadmap(self, setup):
        self.browser = setup
        self.browser.get(self.baseURL)
        self.RoadmapData = ProjectRoadmapData()
        self.lg = Login(self.browser)
        time.sleep(3)
        self.lg.clickLogin()
        time.sleep(3)
        self.lg.setEmail(self.email)
        self.lg.setpassword(self.password)
        time.sleep(3)
        self.lg.submit()
        time.sleep(3)
        self.rm = Roadmap(self.browser)
        time.sleep(10)
        self.rm.clickProjectTab()
        time.sleep(10)
        self.rm.selectProject()
        time.sleep(3)
        self.rm.clickRoadmapTab()
        time.sleep(3)
        self.rm.clickAddTaskBtn()
        time.sleep(5)

        # bug-have to click twice

        self.rm.clickAddTaskBtn()
        time.sleep(5)
        self.rm.enterTaskName(self.RoadmapData.taskName)
        time.sleep(3)
        self.rm.clickAssigner()
        time.sleep(3)
        self.rm.selectAssigner()
        time.sleep(3)
        self.rm.clickTemporaryClick()
        time.sleep(3)
        self.rm.clickShowStartDate()
        time.sleep(3)
        self.rm.clickStartDate()
        time.sleep(3)
        self.rm.selectStartDate()
        time.sleep(3)
        self.rm.clickEndDate()
        time.sleep(3)
        self.rm.selectEndDate()
        time.sleep(3)
        self.rm.clickHour()
        time.sleep(3)
        self.rm.enterHour(self.RoadmapData.estimatedHour)
        time.sleep(3)
        self.rm.clickAddSubTask()
        time.sleep(3)
        self.rm.enterSubtask(self.RoadmapData.subTask)
        time.sleep(3)
        self.rm.clickDrawerClose()
        time.sleep(3)
        # self.rm.openSubTask()
        # time.sleep(3)
        # self.rm.clickShowStartDate()
        # time.sleep(3)
        # self.rm.clickStartDate()
        # time.sleep(3)
        # self.rm.selectStartDate()
        # time.sleep(3)
        # self.rm.clickEndDate()
        # time.sleep(3)
        # self.rm.selectEndDateToSubTask()
        # time.sleep(3)
        # self.rm.clickBackBtn()
        # time.sleep(3)

        # Bug - when close back button not navigate to parent task so can not execute flowing command.

        # self.rm.clickDrawerClose()
        # time.sleep(5)

        # self.rm.parentTaskRightClick()
        # time.sleep(5)

        # Bug - After right click, coming "add subtask btn" not work so can not execute flowing command.
        # self.rm.clickAddSubTask()

        self.rm.clickExpandAllBtn()
        time.sleep(3)
        self.rm.clickCollapseBtn()
        time.sleep(3)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomInBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(2)
        self.rm.clickZoomOutBtn()
        time.sleep(3)
        self.rm.clickZoomInFitBtn()
        time.sleep(3)
        self.rm.clickShowPhase()
        time.sleep(5)
