from page_objects.TaskOpenView.TaskInfo import TaskInfo
from page_objects.TaskOpenView.TaskTimeLog import TaskTimeLog
from page_objects.Login.login import Login
import time
from test_data.test_data import TaskOpenViewData
from utilities.readProperties import ReadConfig
from self import self


class Test_task_open_view:
    baseURL = ReadConfig.get_application_url(self)
    email = ReadConfig.get_email()
    password = ReadConfig.get_password()

    def test_task_timeLog(self, setup):
        self.browser = setup
        self.browser.get(self.baseURL)
        self.tasTimeLogData = TaskOpenViewData()
        self.lg = Login(self.browser)
        self.lg.clickLogin()
        time.sleep(3)
        self.lg.setEmail(self.email)
        self.lg.setpassword(self.password)
        time.sleep(3)
        self.lg.submit()
        time.sleep(20)
        self.ti = TaskInfo(self.browser)
        time.sleep(3)
        self.ti.clickProjectTab()
        time.sleep(3)
        self.ti.selectProject()
        time.sleep(3)
        self.ti.clickOpen()
        time.sleep(5)
        self.tg = TaskTimeLog(self.browser)
        self.tg.clickTimeLogBtn()
        time.sleep(3)
        self.tg.clickTimePlayBtn()
        time.sleep(8)
        self.tg.clickTimeStopBtn()
        time.sleep(3)
        self.tg.editTimeEditBtn()
        time.sleep(3)
        self.tg.setHours(self.tasTimeLogData.hours)
        time.sleep(3)
        self.tg.setMinutes(self.tasTimeLogData.minutes)
        time.sleep(3)
        self.tg.setSeconds(self.tasTimeLogData.seconds)
        time.sleep(3)
        self.tg.clickDatePicker()
        time.sleep(3)
        self.tg.selectDate()
        time.sleep(3)
        self.tg.enterDescription(self.tasTimeLogData.description)
        time.sleep(3)
        self.tg.updateBtn()
        time.sleep(3)
        self.tg.deleteTimeDeleteBtn()
        time.sleep(3)
        self.tg.clickOkBtn()
        time.sleep(3)
        self.tg.clickAddTimeLog()
        time.sleep(3)
        self.tg.setHours(self.tasTimeLogData.hours)
        time.sleep(3)
        self.tg.setMinutes(self.tasTimeLogData.minutes)
        time.sleep(3)
        self.tg.setSeconds(self.tasTimeLogData.seconds)
        time.sleep(3)
        self.tg.clickDatePicker()
        time.sleep(3)
        self.tg.selectDate()
        time.sleep(3)
        self.tg.enterDescription(self.tasTimeLogData.description)
        time.sleep(3)
        self.tg.updateBtn()
        time.sleep(5)
        self.tg.clickExportToExcelBtn()
        time.sleep(5)
