from page_objects.TaskOpenView.TaskInfo import TaskInfo
from page_objects.Login.login import Login
import time
from test_data.test_data import TaskOpenViewData
from utilities.readProperties import ReadConfig
from self import self


class Test_task_open_view:
    baseURL = ReadConfig.get_application_url(self)
    email = ReadConfig.get_email()
    password = ReadConfig.get_password()

    def test_task_info(self, setup):
        self.browser = setup
        self.browser.get(self.baseURL)
        self.taskInfoData = TaskOpenViewData()
        self.lg = Login(self.browser)
        self.lg.clickLogin()
        time.sleep(3)
        self.lg.setEmail(self.email)
        self.lg.setpassword(self.password)
        time.sleep(3)
        self.lg.submit()
        time.sleep(10)
        self.ti = TaskInfo(self.browser)
        time.sleep(3)
        self.ti.clickProjectTab()
        time.sleep(3)
        self.ti.selectProject()
        time.sleep(3)
        self.ti.clickOpen()
        time.sleep(5)
        self.ti.clickAssignMembers()
        time.sleep(3)
        self.ti.enterAssignName(self.taskInfoData.assigner)
        time.sleep(3)
        self.ti.selectAssignMember()
        time.sleep(3)
        self.ti.clickTemp()
        time.sleep(3)
        self.ti.clickShowStartDate()
        time.sleep(3)
        self.ti.clickStartDate()
        time.sleep(3)
        self.ti.setStartDate()
        time.sleep(3)
        self.ti.clickEndDate()
        time.sleep(3)
        self.ti.setEndDate()
        time.sleep(3)
        self.ti.setHours(self.taskInfoData.hours)
        time.sleep(3)
        self.ti.setMinutes(self.taskInfoData.minutes)
        time.sleep(3)
        self.ti.clickPriority()
        time.sleep(3)
        self.ti.selectHighPriority()
        time.sleep(3)
        self.ti.clickLabels()
        time.sleep(3)
        self.ti.createLabel(self.taskInfoData.labelName)
        time.sleep(3)
        self.ti.clickTemp()
        time.sleep(3)
        self.ti.clickNotify()
        time.sleep(3)
        self.ti.enterNotifyMember(self.taskInfoData.notifyMember)
        time.sleep(3)
        self.ti.selectNotifyMember()
        time.sleep(3)
        self.ti.clickTemp()
        time.sleep(3)
        self.ti.enterDescription()
        time.sleep(5)
        self.ti.clickDescriptionEditLink()
        time.sleep(3)
        self.ti.enterURLEditLink(self.taskInfoData.URL)
        time.sleep(3)
        self.ti.enterTextDisplay(self.taskInfoData.displayTest)
        time.sleep(3)
        self.ti.enterTitleEditLink(self.taskInfoData.Title)
        time.sleep(3)
        self.ti.clickOpenLinkDropDown()
        time.sleep(3)
        self.ti.selectOpenLinkDropDown()
        time.sleep(3)
        self.ti.saveOpenLink()
        time.sleep(3)
        self.ti.clickDescriptionParagraph()
        time.sleep(3)
        self.ti.selectDescriptionHeading2()
        time.sleep(3)
        self.ti.clickDescriptionNumbersList()
        time.sleep(3)
        self.ti.clickDescriptionBulatList()
        time.sleep(3)
        self.ti.clickBold()
        time.sleep(3)
        self.ti.clickItalian()
        time.sleep(3)
        self.ti.clickUnderline()
        time.sleep(3)
        self.ti.clickStrikethrough()
        time.sleep(3)
        self.ti.clickAlignLeft()
        time.sleep(3)
        self.ti.clickCenter()
        time.sleep(3)
        self.ti.clickAlignRight()
        time.sleep(3)
        self.ti.clickJustify()
        time.sleep(3)
        self.ti.closeDescription()
        time.sleep(3)
        self.ti.closeDescription()
        time.sleep(3)
        # self.ti.clickLink()
        # time.sleep(5)
        # self.browser.back()
        # time.sleep(5)
        self.ti.clickRefreshBtn()
        time.sleep(3)
        self.ti.clickSubtask()
        time.sleep(3)
        self.ti.enterSubTask(self.taskInfoData.subTask)
        time.sleep(3)
        self.ti.clickPty()
        time.sleep(3)
        self.ti.clickPtyDropDown()
        time.sleep(3)
        self.ti.selectPryDropDown()
        time.sleep(3)
        self.ti.clickBack()
        time.sleep(3)
        self.ti.clickStatus()
        time.sleep(3)
        self.ti.clickStatusDropDown()
        time.sleep(3)
        self.ti.clickBack()
        time.sleep(5)
        self.ti.clickAssigner()
        time.sleep(3)
        self.ti.clickAssignerIcon()
        time.sleep(3)
        self.ti.selectAssigner()
        time.sleep(3)
        self.ti.clickBack()
        time.sleep(3)
        self.ti.clickSubTaskEditBtn()
        time.sleep(3)
        self.ti.clickBack()
        time.sleep(3)
        self.ti.clickSubTaskDeleteBtn()
        time.sleep(3)
        self.ti.selectImage()
        time.sleep(5)
        self.ti.enterComment(self.taskInfoData.comment)
        time.sleep(3)
        self.ti.submitComments()
        time.sleep(3)
        self.ti.deleteComment()
        time.sleep(3)
        self.ti.deleteOkBtn()
        time.sleep(3)
