from page_objects.Phase.Phase import phase
from page_objects.Login.login import Login
import time
from test_data.test_data import PhaseData
from utilities.readProperties import ReadConfig
from self import self


class TestPhase:
    baseURL = ReadConfig.get_application_url(self)
    email = ReadConfig.get_email()
    password = ReadConfig.get_password()

    def test_phase(self, setup):
        self.browser = setup
        self.browser.get(self.baseURL)
        self.phase = PhaseData()
        self.lg = Login(self.browser)
        self.lg.clickLogin()
        time.sleep(3)
        self.lg.setEmail(self.email)
        time.sleep(3)
        self.lg.setpassword(self.password)
        time.sleep(3)
        self.lg.submit()
        time.sleep(10)
        self.phs = phase(self.browser)
        time.sleep(3)
        self.phs.clickProjectTab()
        time.sleep(10)
        self.phs.selectProject()
        time.sleep(3)
        self.phs.projectGroupBy()
        time.sleep(3)
        self.phs.selectPhase()
        time.sleep(5)
        self.phs.clickPhaseSettings()
        time.sleep(3)
        self.phs.clickAddPhaseOptionBtn()
        time.sleep(3)
        self.phs.enterPhaseOption01(self.phase.phaseOption01)
        time.sleep(3)
        self.phs.clickAddPhaseOptionBtn()
        time.sleep(3)
        self.phs.enterPhaseOption02(self.phase.phaseOption02)
        time.sleep(3)
        self.phs.clickAddPhaseOptionBtn()
        time.sleep(3)
        self.phs.enterPhaseOption03(self.phase.phaseOption03)
        time.sleep(3)
        self.phs.phaseOptionDelete()
        time.sleep(5)
        self.phs.closeDrawer()
        time.sleep(3)
        self.phs.clickPhaseMenu()
        time.sleep(3)
        self.phs.clickRename()
        time.sleep(3)
        self.phs.renamePhaseOption(self.phase.renamePhase)
        time.sleep(3)
        self.phs.clickUnmappedAddTask()
        time.sleep(3)
        self.phs.enterUnmappedTask(self.phase.taskName)
        time.sleep(5)
        self.phs.clickPlaning()
        time.sleep(3)
        self.phs.clickAddPlaningTask()
        time.sleep(3)
        self.phs.enterPlaningTask(self.phase.taskName2)
        time.sleep(3)
        self.phs.taskRightClick()
        time.sleep(3)
        self.phs.taskMoveTo()
        time.sleep(3)
        self.phs.selectMovePhase()
        time.sleep(10)
        self.phs.taskRightClick()
        time.sleep(3)
        self.phs.convertToSubTask()
        time.sleep(3)
        self.phs.selectParentTask()
        time.sleep(3)
        self.phs.subTaskView()
        time.sleep(3)
        self.phs.subTaskRightClick()
        time.sleep(3)
        self.phs.convertToTask()
        time.sleep(10)
